# -*- coding: utf-8 -*-
"""AI_HEALTHCARE_LAB_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1P7txX5GFDIdsHDSdcueO5anU3zn099
"""

# Install first:
# pip install kagglehub

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score
)


# Download Kaggle dataset
class DataExplorer:

    def __init__(self):
        self.df = None

    def load_data(self):

        # Download dataset
        path = kagglehub.dataset_download(
            "uciml/breast-cancer-wisconsin-data"
        )

        # Find CSV file
        import os

        files = os.listdir(path)
        csv_file = [
            file for file in files
            if file.endswith(".csv")
        ][0]

        self.df = pd.read_csv(
            os.path.join(path, csv_file)
        )

        # Remove unnamed column
        self.df = self.df.loc[
            :,
            ~self.df.columns.str.contains("^Unnamed")
        ]

        return self.df

    def explore(self):

        print("\n--- Dataset Shape ---")
        print(self.df.shape)

        print("\n--- Summary Statistics ---")
        print(self.df.describe())

        print("\n--- Missing Values ---")
        print(self.df.isnull().sum())

        print("\n--- Duplicate Rows ---")
        print(self.df.duplicated().sum())

        # Remove duplicates
        self.df.drop_duplicates(inplace=True)

        # Check numeric outliers
        numeric_columns = self.df.select_dtypes(
            include=np.number
        ).columns

        print("\n--- Outlier Counts ---")

        for column in numeric_columns:

            Q1 = self.df[column].quantile(0.25)
            Q3 = self.df[column].quantile(0.75)
            IQR = Q3 - Q1

            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR

            outliers = (
                (self.df[column] < lower) |
                (self.df[column] > upper)
            ).sum()

            print(column, ":", outliers)

    def visualize(self):

        # Show class distribution
        plt.figure(figsize=(6, 4))
        sns.countplot(
            x="diagnosis",
            data=self.df
        )
        plt.title("Class Distribution")
        plt.show()

        # Show feature histograms
        self.df.hist(figsize=(15, 12))
        plt.tight_layout()
        plt.show()

        # Show feature boxplots
        numeric_columns = self.df.select_dtypes(
            include=np.number
        ).columns

        plt.figure(figsize=(15, 8))
        self.df[numeric_columns].boxplot()
        plt.xticks(rotation=90)
        plt.title("Feature Boxplots")
        plt.show()

        # Show correlation heatmap
        plt.figure(figsize=(12, 8))
        sns.heatmap(
            self.df[numeric_columns].corr(),
            annot=False,
            cmap="coolwarm"
        )
        plt.title("Correlation Heatmap")
        plt.show()


# Prepare machine learning data
class DataPreprocessor:

    def __init__(self, df):
        self.df = df.copy()

    def prepare(self):

        # Encode target variable
        self.df["diagnosis"] = self.df[
            "diagnosis"
        ].map({
            "B": 0,
            "M": 1
        })

        # Separate features target
        X = self.df.drop(
            "diagnosis",
            axis=1
        )

        y = self.df["diagnosis"]

        # Remove identifier column
        if "id" in X.columns:
            X = X.drop(
                "id",
                axis=1
            )

        # Stratified data split
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.20,
            random_state=42,
            stratify=y
        )

        # Standardize feature values
        scaler = StandardScaler()

        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        return (
            X_train,
            X_test,
            y_train,
            y_test
        )


# Train logistic regression
class LogisticRegressionModel:

    def __init__(self):

        # Create logistic model
        self.model = LogisticRegression(
            max_iter=1000
        )

    def train(self, X_train, y_train):

        # Train the model
        self.model.fit(
            X_train,
            y_train
        )

    def predict(self, X_test):

        # Generate predictions
        return self.model.predict(X_test)

    def probabilities(self, X_test):

        # Get positive probabilities
        return self.model.predict_proba(
            X_test
        )[:, 1]


# Evaluate trained model
class ModelEvaluator:

    def __init__(
        self,
        y_test,
        predictions,
        probabilities
    ):

        self.y_test = y_test
        self.predictions = predictions
        self.probabilities = probabilities

    def evaluate(self):

        # Calculate accuracy
        accuracy = accuracy_score(
            self.y_test,
            self.predictions
        )

        # Calculate precision
        precision = precision_score(
            self.y_test,
            self.predictions,
            average=None
        )

        # Calculate recall
        recall = recall_score(
            self.y_test,
            self.predictions,
            average=None
        )

        # Calculate F1 score
        f1 = f1_score(
            self.y_test,
            self.predictions,
            average=None
        )

        # Calculate ROC-AUC
        auc = roc_auc_score(
            self.y_test,
            self.probabilities
        )

        print("\n--- Evaluation Results ---")

        print("Accuracy :", accuracy)

        print("\nPrecision:")
        print("Benign    :", precision[0])
        print("Malignant :", precision[1])

        print("\nRecall:")
        print("Benign    :", recall[0])
        print("Malignant :", recall[1])

        print("\nF1 Score:")
        print("Benign    :", f1[0])
        print("Malignant :", f1[1])

        print("\nROC-AUC :", auc)

        # Print classification report
        print("\n--- Classification Report ---")

        print(
            classification_report(
                self.y_test,
                self.predictions,
                target_names=[
                    "Benign",
                    "Malignant"
                ]
            )
        )

        # Create confusion matrix
        cm = confusion_matrix(
            self.y_test,
            self.predictions
        )

        disp = ConfusionMatrixDisplay(
            confusion_matrix=cm,
            display_labels=[
                "Benign",
                "Malignant"
            ]
        )

        disp.plot()
        plt.title("Confusion Matrix")
        plt.show()

        # Calculate ROC values
        fpr, tpr, thresholds = roc_curve(
            self.y_test,
            self.probabilities
        )

        # Plot ROC curve
        plt.figure(figsize=(7, 5))

        plt.plot(
            fpr,
            tpr,
            label=f"AUC = {auc:.3f}"
        )

        plt.plot(
            [0, 1],
            [0, 1],
            linestyle="--"
        )

        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("ROC Curve")
        plt.legend()
        plt.show()


# Create complete pipeline
class BreastCancerPipeline:

    def run(self):

        # Load dataset
        explorer = DataExplorer()

        df = explorer.load_data()

        # Explore dataset
        explorer.explore()

        explorer.visualize()

        # Prepare training data
        preprocessor = DataPreprocessor(df)

        (
            X_train,
            X_test,
            y_train,
            y_test
        ) = preprocessor.prepare()

        # Create model
        model = LogisticRegressionModel()

        # Train model
        model.train(
            X_train,
            y_train
        )

        # Generate predictions
        predictions = model.predict(
            X_test
        )

        probabilities = model.probabilities(
            X_test
        )

        # Evaluate predictions
        evaluator = ModelEvaluator(
            y_test,
            predictions,
            probabilities
        )

        evaluator.evaluate()


# Run complete assignment
pipeline = BreastCancerPipeline()

pipeline.run()