# -*- coding: utf-8 -*-
"""Lab_3_Ai_in_Healthcare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mfru6a0whH-TWCsWdaumUBTLmZeHKUEB
"""

!pip install -q kaggle wfdb nltk opencv-python tensorflow scikit-learn


import os
import re
import glob
import zipfile
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

from scipy import stats
from scipy.signal import butter, filtfilt

from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_extraction.text import TfidfVectorizer

from tensorflow.keras.preprocessing.image import ImageDataGenerator

import wfdb
import nltk

warnings.filterwarnings("ignore")

nltk.download("stopwords", quiet=True)

from nltk.corpus import stopwords

sns.set_theme(style="whitegrid")

print("Libraries loaded successfully!")



print("\n" + "="*70)
print("PART A — TABULAR DATA")
print("="*70)



pima_url = (
    "https://raw.githubusercontent.com/"
    "jbrownlee/Datasets/master/"
    "pima-indians-diabetes.data.csv"
)

columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

df = pd.read_csv(
    pima_url,
    names=columns
)

print("\nPima Dataset loaded successfully!")

print("\nFirst 5 rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
display(df.describe())



print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())



medical_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for col in medical_columns:
    df[col] = df[col].replace(0, np.nan)

print("\nMissing values after detecting invalid zeros:")
print(df.isnull().sum())


for col in medical_columns:
    df[col] = df[col].fillna(df[col].median())

print("\nMissing values after median imputation:")
print(df.isnull().sum())


duplicates = df.duplicated().sum()

print("\nNumber of duplicate rows:", duplicates)

if duplicates > 0:
    df = df.drop_duplicates()

print("Shape after duplicate removal:", df.shape)


plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="Outcome"
)

plt.title("Diabetes Outcome Distribution")
plt.xlabel("Outcome (0 = No Diabetes, 1 = Diabetes)")
plt.ylabel("Number of Patients")

plt.show()



plt.figure(figsize=(9,5))

sns.histplot(
    data=df,
    x="Glucose",
    hue="Outcome",
    kde=True
)

plt.title("Glucose Distribution by Diabetes Outcome")

plt.show()



plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x="BMI",
    y="Glucose",
    hue="Outcome"
)

plt.title("BMI vs Glucose")

plt.show()



plt.figure(figsize=(10,8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Pima Diabetes Correlation Matrix")

plt.show()


diabetic = df[
    df["Outcome"] == 1
]["Glucose"]

non_diabetic = df[
    df["Outcome"] == 0
]["Glucose"]

t_stat, p_value = stats.ttest_ind(
    diabetic,
    non_diabetic,
    equal_var=False
)

print("\n" + "-"*50)
print("HYPOTHESIS TEST — T-TEST")
print("-"*50)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Conclusion: Reject H0.")
    print("There is a statistically significant difference in glucose levels.")
else:
    print("Conclusion: Fail to reject H0.")
    print("There is no statistically significant difference.")




df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 30, 50, 100],
    labels=["Young", "Middle", "Older"]
)

contingency_table = pd.crosstab(
    df["AgeGroup"],
    df["Outcome"]
)

print("\n" + "-"*50)
print("CHI-SQUARE TEST")
print("-"*50)

print("\nContingency Table:")
display(contingency_table)

chi2, chi_p, dof, expected = stats.chi2_contingency(
    contingency_table
)

print("Chi-square statistic:", chi2)
print("P-value:", chi_p)
print("Degrees of freedom:", dof)

if chi_p < 0.05:
    print("Conclusion: Significant association exists.")
else:
    print("Conclusion: No significant association.")



anova_groups = [
    group["Glucose"].values
    for _, group in df.groupby(
        "AgeGroup",
        observed=True
    )
]

f_stat, anova_p = stats.f_oneway(
    *anova_groups
)

print("\n" + "-"*50)
print("ONE-WAY ANOVA")
print("-"*50)

print("F-statistic:", f_stat)
print("P-value:", anova_p)

if anova_p < 0.05:
    print("Conclusion: Significant difference exists between age groups.")
else:
    print("Conclusion: No significant difference between age groups.")



X = df.drop(
    columns=["Outcome", "AgeGroup"]
)

y = df["Outcome"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

print("\nScaled Data:")
display(X_scaled.head())



selector = SelectKBest(
    score_func=f_classif,
    k=5
)

X_selected = selector.fit_transform(
    X_scaled,
    y
)

selected_features = X.columns[
    selector.get_support()
]

print("\nSelected Features:")
for feature in selected_features:
    print("✓", feature)


print("\n" + "="*70)
print("PART B — TEXT DATA")
print("="*70)



from google.colab import files

print("""
========================================================
KAGGLE SETUP
========================================================
Upload your kaggle.json file.
Get it from:

Kaggle → Settings → API → Create New Token
========================================================
""")

import os
from getpass import getpass

kaggle_token = getpass("Paste your Kaggle API token: ")

os.environ["KAGGLE_API_TOKEN"] = kaggle_token

print("Kaggle authentication configured!")

!kaggle datasets list -s medicaltranscriptions


os.makedirs(
    "/content/mtsamples",
    exist_ok=True
)

!kaggle datasets download \
    -d tboyle10/medicaltranscriptions \
    -p /content/mtsamples



mtsample_zip = (
    "/content/mtsamples/"
    "medicaltranscriptions.zip"
)

if os.path.exists(mtsample_zip):

    with zipfile.ZipFile(
        mtsample_zip,
        "r"
    ) as zip_ref:

        zip_ref.extractall(
            "/content/mtsamples"
        )


# Find CSV
csv_files = glob.glob(
    "/content/mtsamples/**/*.csv",
    recursive=True
)

print("\nCSV files found:")

for file in csv_files:
    print(file)

if len(csv_files) == 0:

    raise FileNotFoundError(
        "MTSamples CSV not found."
    )

text_df = pd.read_csv(
    csv_files[0]
)

print("\nMTSamples loaded!")

print("\nShape:")
print(text_df.shape)

print("\nColumns:")
print(text_df.columns.tolist())

print("\nFirst 5 rows:")
display(text_df.head())



print("\nMissing values:")
print(text_df.isnull().sum())



possible_text_columns = [
    "transcription",
    "Transcription",
    "text",
    "Text"
]

text_column = None

for col in possible_text_columns:

    if col in text_df.columns:

        text_column = col
        break

if text_column is None:

    raise ValueError(
        "Transcription column not automatically detected. "
        "Check the column names above."
    )

print(
    "\nUsing transcription column:",
    text_column
)



def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove special characters
    text = re.sub(
        r"[^a-zA-Z0-9\s]",
        " ",
        text
    )

    # Remove extra whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


text_df["clean_text"] = (
    text_df[text_column]
    .apply(clean_text)
)


stop_words = set(
    stopwords.words("english")
)


def remove_stopwords(text):

    words = text.split()

    words = [
        word
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)


text_df["clean_text"] = (
    text_df["clean_text"]
    .apply(remove_stopwords)
)


text_df["word_count"] = (
    text_df["clean_text"]
    .apply(
        lambda x: len(x.split())
    )
)

print("\nText statistics:")
display(
    text_df["word_count"].describe()
)



plt.figure(figsize=(9,5))

sns.histplot(
    text_df["word_count"],
    bins=50,
    kde=True
)

plt.title(
    "Medical Transcription Word Count Distribution"
)

plt.xlabel("Number of Words")
plt.ylabel("Frequency")

plt.show()


vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_text = vectorizer.fit_transform(
    text_df["clean_text"]
)

print("\nTF-IDF Matrix Shape:")
print(X_text.shape)



feature_names = (
    vectorizer
    .get_feature_names_out()
)

tfidf_scores = np.asarray(
    X_text.mean(axis=0)
).flatten()

top_indices = (
    tfidf_scores
    .argsort()[-20:][::-1]
)

print("\nTop 20 TF-IDF Terms:")

for i in top_indices:

    print(
        feature_names[i],
        "->",
        round(
            tfidf_scores[i],
            4
        )
    )


print("\n" + "="*70)
print("PART C — IMAGE DATA")
print("="*70)


os.makedirs(
    "/content/chest_xray",
    exist_ok=True
)

!kaggle datasets download \
    -d paultimothymooney/chest-xray-pneumonia \
    -p /content/chest_xray



xray_zips = glob.glob(
    "/content/chest_xray/*.zip"
)

print("\nX-Ray ZIP files:")

for z in xray_zips:
    print(z)

for z in xray_zips:

    with zipfile.ZipFile(
        z,
        "r"
    ) as zip_ref:

        zip_ref.extractall(
            "/content/chest_xray"
        )

print("\nX-Ray dataset extracted!")



normal_images = glob.glob(
    "/content/chest_xray/**/NORMAL/*",
    recursive=True
)

pneumonia_images = glob.glob(
    "/content/chest_xray/**/PNEUMONIA/*",
    recursive=True
)

# Keep only image files
valid_extensions = (
    ".jpeg",
    ".jpg",
    ".png"
)

normal_images = [
    x for x in normal_images
    if x.lower().endswith(valid_extensions)
]

pneumonia_images = [
    x for x in pneumonia_images
    if x.lower().endswith(valid_extensions)
]

print("\nNormal images:", len(normal_images))
print("Pneumonia images:", len(pneumonia_images))



plt.figure(figsize=(7,5))

plt.bar(
    ["Normal", "Pneumonia"],
    [
        len(normal_images),
        len(pneumonia_images)
    ]
)

plt.title(
    "Chest X-Ray Class Distribution"
)

plt.ylabel(
    "Number of Images"
)

plt.show()


if (
    len(normal_images) > 0
    and
    len(pneumonia_images) > 0
):

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(12,5)
    )

    normal_img = Image.open(
        normal_images[0]
    )

    pneumonia_img = Image.open(
        pneumonia_images[0]
    )

    axes[0].imshow(
        normal_img,
        cmap="gray"
    )

    axes[0].set_title(
        "Normal X-Ray"
    )

    axes[0].axis("off")

    axes[1].imshow(
        pneumonia_img,
        cmap="gray"
    )

    axes[1].set_title(
        "Pneumonia X-Ray"
    )

    axes[1].axis("off")

    plt.show()


IMG_SIZE = (
    224,
    224
)


def preprocess_image(path):

    img = Image.open(path)

    # Convert to grayscale
    img = img.convert("L")

    # Resize
    img = img.resize(
        IMG_SIZE
    )

    # Convert to NumPy
    img = np.array(img)

    # Normalize pixels
    img = img / 255.0

    return img


if len(normal_images) > 0:

    processed_img = preprocess_image(
        normal_images[0]
    )

    print(
        "\nProcessed image shape:",
        processed_img.shape
    )

    print(
        "Minimum pixel value:",
        processed_img.min()
    )

    print(
        "Maximum pixel value:",
        processed_img.max()
    )



if len(normal_images) > 0:

    original_img = cv2.imread(
        normal_images[0],
        cv2.IMREAD_GRAYSCALE
    )

    filtered_img = cv2.GaussianBlur(
        original_img,
        (5,5),
        0
    )

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(12,5)
    )

    axes[0].imshow(
        original_img,
        cmap="gray"
    )

    axes[0].set_title(
        "Original X-Ray"
    )

    axes[0].axis("off")

    axes[1].imshow(
        filtered_img,
        cmap="gray"
    )

    axes[1].set_title(
        "Gaussian Noise Reduction"
    )

    axes[1].axis("off")

    plt.show()


image_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=10,

    width_shift_range=0.1,

    height_shift_range=0.1,

    zoom_range=0.1,

    horizontal_flip=True
)


# Find the training directory automatically
train_dirs = glob.glob(
    "/content/chest_xray/**/train",
    recursive=True
)

if len(train_dirs) > 0:

    train_directory = train_dirs[0]

    print(
        "\nTraining directory:",
        train_directory
    )

    train_generator = (
        image_datagen.flow_from_directory(

            train_directory,

            target_size=(
                224,
                224
            ),

            batch_size=32,

            class_mode="binary",

            color_mode="grayscale"
        )
    )

    print(
        "\nClass mapping:"
    )

    print(
        train_generator.class_indices
    )

else:

    print(
        "\nTraining directory not found."
    )



print("\n" + "="*70)
print("PART D — SIGNAL DATA")
print("="*70)


record = wfdb.rdrecord(
    "100",
    pn_dir="mitdb"
)

print(
    "\nMIT-BIH record loaded!"
)

print(
    "Sampling frequency:",
    record.fs
)

print(
    "Signal shape:",
    record.p_signal.shape
)

ecg = record.p_signal[:, 0]

print(
    "\nNumber of ECG samples:",
    len(ecg)
)



plt.figure(
    figsize=(15,5)
)

plt.plot(
    ecg[:3000]
)

plt.title(
    "MIT-BIH ECG Signal — Record 100"
)

plt.xlabel(
    "Sample"
)

plt.ylabel(
    "Amplitude"
)

plt.show()


ecg_normalized = (
    ecg - np.mean(ecg)
) / np.std(ecg)

print(
    "\nNormalized ECG mean:",
    np.mean(ecg_normalized)
)

print(
    "Normalized ECG standard deviation:",
    np.std(ecg_normalized)
)


def bandpass_filter(
    signal,
    lowcut,
    highcut,
    fs,
    order=4
):

    nyquist = 0.5 * fs

    low = (
        lowcut /
        nyquist
    )

    high = (
        highcut /
        nyquist
    )

    b, a = butter(
        order,
        [
            low,
            high
        ],
        btype="band"
    )

    filtered = filtfilt(
        b,
        a,
        signal
    )

    return filtered


filtered_ecg = bandpass_filter(

    ecg,

    lowcut=0.5,

    highcut=40,

    fs=record.fs
)


plt.figure(
    figsize=(15,5)
)

plt.plot(
    ecg[:3000],
    label="Original"
)

plt.plot(
    filtered_ecg[:3000],
    label="Filtered"
)

plt.title(
    "ECG Noise Removal Using Bandpass Filter"
)

plt.xlabel(
    "Sample"
)

plt.ylabel(
    "Amplitude"
)

plt.legend()

plt.show()


window_size = 500

windows = []

for i in range(
    0,
    len(filtered_ecg) - window_size,
    window_size
):

    window = filtered_ecg[
        i:i + window_size
    ]

    windows.append(
        window
    )

windows = np.array(
    windows
)

print(
    "\nECG windows shape:",
    windows.shape
)

print(
    "Each window contains",
    window_size,
    "samples."
)


def extract_ecg_features(window):

    return {

        "mean":
            np.mean(window),

        "std":
            np.std(window),

        "min":
            np.min(window),

        "max":
            np.max(window),

        "median":
            np.median(window),

        "range":
            np.max(window)
            -
            np.min(window),

        "energy":
            np.sum(
                window ** 2
            )
    }


feature_list = [

    extract_ecg_features(
        window
    )

    for window in windows
]

ecg_features = pd.DataFrame(
    feature_list
)

print(
    "\nExtracted ECG features:"
)

display(
    ecg_features.head()
)



print(
    "\nECG Feature Statistics:"
)

display(
    ecg_features.describe()
)



plt.figure(
    figsize=(9,5)
)

sns.histplot(
    ecg_features["std"],
    kde=True
)

plt.title(
    "ECG Standard Deviation Distribution"
)

plt.xlabel(
    "Standard Deviation"
)

plt.show()

plt.figure(
    figsize=(9,7)
)

sns.heatmap(
    ecg_features.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title(
    "ECG Feature Correlation"
)

plt.show()

print("\n" + "="*70)
print("FINAL ASSIGNMENT SUMMARY")
print("="*70)


summary = {

    "A — Tabular": [
        "Dataset acquisition",
        "Data inspection",
        "Missing value detection",
        "Clinically implausible value handling",
        "Median imputation",
        "Duplicate detection",
        "EDA",
        "Hypothesis testing",
        "Chi-square test",
        "ANOVA",
        "Feature scaling",
        "Feature selection"
    ],

    "B — Text": [
        "Dataset acquisition",
        "Missing value detection",
        "Text cleaning",
        "Lowercase conversion",
        "Special character removal",
        "Stopword removal",
        "Word count analysis",
        "EDA",
        "TF-IDF feature extraction"
    ],

    "C — Image": [
        "Dataset acquisition",
        "Class distribution",
        "Image visualization",
        "Image resizing",
        "Pixel normalization",
        "Noise removal",
        "Image augmentation"
    ],

    "D — Signal": [
        "ECG acquisition",
        "ECG visualization",
        "Normalization",
        "Bandpass filtering",
        "Noise removal",
        "Signal windowing",
        "Feature extraction",
        "EDA"
    ]
}


for modality, tasks in summary.items():

    print(
        "\n" + modality
    )

    for task in tasks:

        print(
            "  ✓",
            task
        )

print("\n" + "="*70)
print("DATASET SOURCES")
print("="*70)

print("""
A. Pima Indians Diabetes:
https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv

B. MTSamples Medical Transcriptions:
https://www.kaggle.com/datasets/tboyle10/medicaltranscriptions

C. Chest X-Ray Pneumonia:
https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia

D. MIT-BIH Arrhythmia:
https://physionet.org/content/mitdb/1.0.0/
""")


print("\nCOMPLETE!")
print("All four medical data modalities have been processed.")